name: Build Windows Executable

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --onefile \
            --add-data=image_processor_service.py:. \
            --add-data=salesforce_api_service.py:. \
            --add-data=static:static \
            --name=main \
            --distpath dist/windows_dist \
            main.py
      - name: List dist directory
        run: ls -la dist/

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: my-executable
          path: dist/windows_dist/main
